spring:
  datasource:
    url: ${LOCAL_URL_USERS}
    username: ${LOCAL_USER}
    password: ${LOCAL_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 30000
      pool-name: HikariPool-Users
      data-source-properties:
        prepareThreshold: 0

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
